[versions]
gradle-starter = "0.49.0"
gradle-kotlinter = "3.11.1"
google-agp = "7.2.2"
maven-kotlin = "1.7.10"
maven-junit = "5.9.0"
maven-assertj = "3.23.1"

[libraries]
starter-gradle = { module = "com.project.starter:android", version.ref = "gradle-starter" }
agp-gradle = { module = "com.android.tools.build:gradle", version.ref = "google-agp" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "maven-junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "maven-assertj" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "maven-kotlin" }

[plugins]
jmailen-kotlinter = { id = "org.jmailen.kotlinter", version.ref = "gradle-kotlinter" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "maven-kotlin" }
